/* Combate em tempo real: dano, fraquezas, resistências, bosses e drops. */
(function(){
  const TYPES=['lobo','urso','espirito','golem','morto-vivo','dragao','demonio','anjo','besta','slime','aranha','serpente','fenix','hidra'];
  const BOSSES=[{name:'Hidra das Sete Chuvas',type:'hidra',hp:900,el:'agua'},{name:'Dragão-Cinza Ignivar',type:'dragao',hp:1200,el:'fogo'},{name:'Arcanjo Quebrado Elyor',type:'anjo',hp:1100,el:'luz'},{name:'Lorde Umbra Sem Face',type:'demonio',hp:1500,el:'trevas'}];
  class CombatSystem{
    constructor(engine){this.engine=engine;this.enemies=[];this.damageText=[];this.spawnTimer=0;this.bossesDefeated=[];}
    update(dt){this.spawnTimer-=dt;if(this.spawnTimer<=0){this.spawnAroundPlayer();this.spawnTimer=2.5+Math.random()*3}const p=this.engine.player;for(const e of this.enemies){const dx=p.x-e.x,dy=p.y-e.y,d=Math.hypot(dx,dy)||1;if(d<e.aggro){e.x+=dx/d*e.speed*dt*(e.slow||1);e.y+=dy/d*e.speed*dt*(e.slow||1)}if(d<32){p.hp-=e.damage*dt;this.engine.audio.play('hit');}e.cool=(e.cool||0)-dt;e.slow=Math.min(1,(e.slow||1)+dt*.25)}for(const pr of this.engine.magic.projectiles){for(const e of this.enemies){if(Math.hypot(pr.x-e.x,pr.y-e.y)<e.size+10){this.hit(e,pr.damage,pr.el);pr.life=0;if(pr.spell.slow)e.slow*=1-pr.spell.slow;break}}}this.enemies=this.enemies.filter(e=>{if(e.hp>0)return true;this.defeat(e);return false});this.damageText=this.damageText.filter(t=>{t.y-=20*dt;t.life-=dt;return t.life>0});}
    spawnAroundPlayer(){if(this.enemies.length>38)return;const p=this.engine.player,b=this.engine.world.biomeAt(p.x,p.y),r=this.engine.world.regionAt(p.x,p.y);const count=1+Math.floor(b.danger*3);for(let i=0;i<count;i++){const a=Math.random()*Math.PI*2,d=420+Math.random()*480;const level=Math.max(1,Math.floor((Math.hypot(r.x,r.y)/650)+this.engine.player.level*.45));const type=TYPES[Math.floor(Math.random()*TYPES.length)];this.enemies.push(this.makeEnemy(p.x+Math.cos(a)*d,p.y+Math.sin(a)*d,type,level,b))}if(Math.random()<.015+b.danger*.02){const boss=BOSSES[Math.floor(Math.random()*BOSSES.length)];this.enemies.push(this.makeEnemy(p.x+600,p.y-500,boss.type,this.engine.player.level+5,b,boss));this.engine.toast(`Chefe secreto desperto: ${boss.name}!`)} }
    makeEnemy(x,y,type,level,biome,boss){const hp=(boss?boss.hp:45+level*18)*(1+biome.danger);return {x,y,type,name:boss?boss.name:this.nameFor(type),level,hp,maxHp:hp,el:boss?boss.el:this.elementFor(type),speed:boss?55:70+Math.random()*45,damage:(boss?22:7+level*1.4),size:boss?34:14+Math.random()*9,aggro:boss?620:360+biome.danger*260,boss:!!boss,color:boss?'#f8d783':biome.detail};}
    nameFor(t){return {lobo:'Lobo rúnico',urso:'Urso musgo',espirito:'Espírito errante',golem:'Golem antigo','morto-vivo':'Morto-vivo coroado',dragao:'Draco jovem',demonio:'Diabrete umbral',anjo:'Anjo exilado',besta:'Besta mágica',slime:'Slime prismático',aranha:'Aranha gigante',serpente:'Serpente cristal',fenix:'Fênix menor',hidra:'Filhote de hidra'}[t]||t}
    elementFor(t){return {lobo:'natureza',urso:'terra',espirito:'arcano',golem:'terra','morto-vivo':'trevas',dragao:'fogo',demonio:'trevas',anjo:'luz',besta:'sangue',slime:'agua',aranha:'natureza',serpente:'relampago',fenix:'fogo',hidra:'agua'}[t]||'arcano'}
    multiplier(target,el){const E=window.GameMagic.ELEMENTS[el]||{};if(E.strong&&E.strong.includes(target.el))return 1.55;if(E.weak&&E.weak.includes(target.el))return .65;return 1}
    hit(e,dmg,el){let m=this.multiplier(e,el);if(Math.random()<this.engine.player.crit)m*=2;const final=Math.round(dmg*m);e.hp-=final;this.damageText.push({x:e.x,y:e.y,text:final+(m>1.6?' CRÍTICO!':m>1?'!':''),color:m>1?'#f8d783':'#fff',life:.8});this.engine.magic.burst(e.x,e.y,window.GameMagic.ELEMENTS[el]?.color||'#fff',m>1?26:12);}
    areaDamage(x,y,r,dmg,el,spell){for(const e of this.enemies){const d=Math.hypot(x-e.x,y-e.y);if(d<r){this.hit(e,dmg*(1-d/r*.45),el);if(spell?.id==='raizes')e.slow=.18;if(spell?.id==='fenda_tempo')e.slow=.08}}}
    defeat(e){const p=this.engine.player;p.xp+=e.level*(e.boss?80:18);p.gold+=e.boss?90:8+e.level;this.engine.inventory.add({id:'essencia_'+e.el,name:`Essência de ${e.el}`,type:'material',qty:e.boss?5:1,rarity:e.boss?'lendário':'comum'});this.engine.quests.notifyKill(e);if(e.boss){this.bossesDefeated.push(e.name);this.engine.achieve('Caçador de Colossos');this.engine.toast(`Boss derrotado: ${e.name}`)}this.engine.audio.play('drop');}
    draw(ctx,camera,w,h){for(const e of this.enemies){const x=e.x-camera.x+w/2,y=e.y-camera.y+h/2;ctx.fillStyle='rgba(0,0,0,.35)';ctx.fillRect(x-e.size,y+e.size,e.size*2,5);ctx.fillStyle=e.color;ctx.beginPath();ctx.arc(x,y,e.size,0,Math.PI*2);ctx.fill();ctx.fillStyle='#100b20';ctx.fillRect(x-e.size,y-e.size-12,e.size*2,5);ctx.fillStyle=e.boss?'#ff4f9f':'#ff7187';ctx.fillRect(x-e.size,y-e.size-12,e.size*2*Math.max(0,e.hp/e.maxHp),5);if(e.boss){ctx.fillStyle='#f8d783';ctx.fillText(e.name,x-50,y-e.size-18)}}for(const t of this.damageText){ctx.globalAlpha=t.life;ctx.fillStyle=t.color;ctx.fillText(t.text,t.x-camera.x+w/2,t.y-camera.y+h/2);ctx.globalAlpha=1}}
  }
  window.GameCombat={CombatSystem};
})();
