/* Motor principal em canvas: loop, input, câmera, renderização e integração de sistemas. */
(function(){
  class Engine{
    constructor(){this.canvas=document.getElementById('gameCanvas');this.ctx=this.canvas.getContext('2d');this.minimap=document.getElementById('minimap').getContext('2d');this.keys={};this.mouse={x:0,y:0,down:false};this.camera={x:0,y:0};this.running=false;this.paused=false;this.last=0;this.player=this.createPlayer();this.world=new GameWorld.World();this.audio=new GameAudio.AudioSystem();this.inventory=new GameInventory.InventorySystem(this);this.quests=new GameQuests.QuestSystem(this);this.magic=new GameMagic.MagicSystem(this);this.combat=new GameCombat.CombatSystem(this);this.npc=new GameNPC.NPCSystem(this);this.weather=new GameWeather.WeatherSystem(this);this.save=new GameSave.SaveSystem(this);this.bind();this.resize();}
    createPlayer(){return {name:'Aerin',sex:'Feminino',race:'Humano',class:'Mago elemental',x:30,y:40,vx:0,vy:0,hp:100,maxHp:100,mana:140,maxMana:140,xp:0,nextXp:120,level:1,gold:40,crit:.08,aura:'#8df7ff',cape:'#4f46e5',titles:['Aprendiz das Estrelas']}}
    bind(){addEventListener('resize',()=>this.resize());addEventListener('keydown',e=>{this.keys[e.key.toLowerCase()]=true;if(['1','2','3','4','5'].includes(e.key)){this.magic.selected=+e.key-1;this.renderHotbar()}if(e.key==='Escape')window.UI.togglePause();if(e.key.toLowerCase()==='i')this.openOverlay('Inventário',this.inventory.html());if(e.key.toLowerCase()==='m')this.openOverlay('Mapa do mundo',this.mapHtml());if(e.key.toLowerCase()==='g')this.openOverlay('Grimório',this.magic.grimoireHtml());if(e.key.toLowerCase()==='q')this.openOverlay('Missões',this.quests.html());if(e.key.toLowerCase()==='e')this.npc.interact();});addEventListener('keyup',e=>this.keys[e.key.toLowerCase()]=false);this.canvas.addEventListener('mousemove',e=>{const r=this.canvas.getBoundingClientRect();this.mouse.x=(e.clientX-r.left)/r.width*this.canvas.width;this.mouse.y=(e.clientY-r.top)/r.height*this.canvas.height});this.canvas.addEventListener('mousedown',()=>{this.audio.init();this.mouse.down=true;this.castAtMouse()});this.canvas.addEventListener('mouseup',()=>this.mouse.down=false)}
    resize(){this.canvas.width=Math.floor(innerWidth*devicePixelRatio);this.canvas.height=Math.floor(innerHeight*devicePixelRatio);this.ctx.imageSmoothingEnabled=false;}
    start(profile){Object.assign(this.player,profile||{});this.running=true;this.paused=false;this.last=performance.now();this.renderHotbar();requestAnimationFrame(t=>this.loop(t));}
    loop(t){if(!this.running)return;const dt=Math.min(.033,(t-this.last)/1000||0);this.last=t;if(!this.paused)this.update(dt);this.draw();requestAnimationFrame(tt=>this.loop(tt));}
    update(dt){this.handleMovement(dt);this.world.update(dt);this.weather.update(dt);this.magic.update(dt);this.combat.update(dt);this.npc.update(dt);this.save.update(dt);this.levelCheck();this.updateHud();this.audio.ambience(this.world);}
    handleMovement(dt){const p=this.player;let dx=(this.keys.d||this.keys.arrowright?1:0)-(this.keys.a||this.keys.arrowleft?1:0),dy=(this.keys.s||this.keys.arrowdown?1:0)-(this.keys.w||this.keys.arrowup?1:0);const l=Math.hypot(dx,dy)||1;const speed=(this.inventory.equipment.montaria?240:165)*(this.keys.shift?1.35:1);p.x+=dx/l*speed*dt;p.y+=dy/l*speed*dt;if(dx||dy){this.audio.play('step');this.magic.emit(p.x,p.y,p.aura,1)}p.mana=Math.min(p.maxMana,p.mana+10*dt);this.camera.x+=(p.x-this.camera.x)*.12;this.camera.y+=(p.y-this.camera.y)*.12;}
    castAtMouse(){const wx=this.camera.x-this.canvas.width/2+this.mouse.x,wy=this.camera.y-this.canvas.height/2+this.mouse.y;this.magic.cast(wx,wy);}
    levelCheck(){const p=this.player;if(p.xp>=p.nextXp){p.xp-=p.nextXp;p.level++;p.nextXp=Math.floor(p.nextXp*1.34);p.maxHp+=12;p.maxMana+=18;p.hp=p.maxHp;p.mana=p.maxMana;this.magic.skillPoints++;this.toast(`Nível ${p.level}! Ponto de habilidade recebido.`);if(p.level>=3)this.magic.unlock('raizes');if(p.level>=5)this.magic.unlock('meteoro');}}
    draw(){const c=this.ctx,w=this.canvas.width,h=this.canvas.height;this.weather.drawSky(c,w,h);this.world.draw(c,this.camera,w,h);this.npc.draw(c,this.camera,w,h);this.drawPlayer(c,w,h);this.combat.draw(c,this.camera,w,h);this.magic.draw(c,this.camera,w,h);this.weather.draw(c,w,h);this.world.drawMinimap(this.minimap,this.player);document.getElementById('regionBadge').textContent=this.world.regionAt(this.player.x,this.player.y).city+' — Dia '+this.world.day+' '+String(Math.floor(this.world.time)).padStart(2,'0')+'h';}
    drawPlayer(ctx,w,h){const p=this.player,x=p.x-this.camera.x+w/2,y=p.y-this.camera.y+h/2;ctx.save();ctx.translate(x,y);ctx.fillStyle='rgba(0,0,0,.35)';ctx.fillRect(-14,18,28,6);ctx.strokeStyle=p.aura;ctx.shadowColor=p.aura;ctx.shadowBlur=22;ctx.beginPath();ctx.arc(0,0,24+Math.sin(performance.now()/180)*3,0,Math.PI*2);ctx.stroke();ctx.shadowBlur=0;ctx.fillStyle=p.cape;ctx.fillRect(-10,-4,20,28);ctx.fillStyle='#f5c7a7';ctx.fillRect(-7,-18,14,14);ctx.fillStyle='#2b1a45';ctx.fillRect(-9,-24,18,8);ctx.strokeStyle='#f8d783';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(13,-8);ctx.lineTo(25,-32);ctx.stroke();ctx.fillStyle=p.aura;ctx.fillRect(22,-36,7,7);if(this.inventory.equipment.pet){ctx.fillStyle='#111';ctx.fillRect(-34,-8,12,10);ctx.fillStyle=p.aura;ctx.fillRect(-28,-13,3,3)}ctx.restore();}
    updateHud(){const p=this.player;document.getElementById('hpText').textContent=`${Math.ceil(p.hp)}/${p.maxHp}`;document.getElementById('mpText').textContent=`${Math.ceil(p.mana)}/${p.maxMana}`;document.getElementById('hpBar').style.width=Math.max(0,p.hp/p.maxHp*100)+'%';document.getElementById('mpBar').style.width=Math.max(0,p.mana/p.maxMana*100)+'%';document.getElementById('xpBar').style.width=Math.max(0,p.xp/p.nextXp*100)+'%';if(p.hp<=0){p.hp=p.maxHp;p.x=p.y=40;this.toast('Você foi resgatado por curandeiros lunares.')}}
    renderHotbar(){const h=document.getElementById('hotbar');h.innerHTML=this.magic.hotbar.map((s,i)=>`<div class="slot ${i===this.magic.selected?'active':''}"><kbd>${i+1}</kbd><span>${GameMagic.ELEMENTS[s.el].icon}</span><small>${s.name}</small></div>`).join('')}
    openOverlay(title,html){window.UI.openOverlay(title,html)}
    showDialogue(n){const d=document.getElementById('dialogue');d.innerHTML=`<h3>${n.name} — ${n.race} ${n.job}</h3><p>${n.dialog}</p><small>Facção: ${n.faction}</small>`;d.classList.remove('hidden');clearTimeout(this.dialogTimer);this.dialogTimer=setTimeout(()=>d.classList.add('hidden'),7000)}
    mapHtml(){return `<div class="grid">${this.world.regions.map(r=>`<article class="card"><h3>${r.city}</h3><p>${GameWorld.BIOMES[r.biome].lore}</p><span class="tag">${GameWorld.BIOMES[r.biome].name}</span><span class="tag">${r.faction}</span></article>`).join('')}</div>`}
    settingsHtml(){return `<div class="grid"><article class="card"><h3>Configurações</h3><button data-audio="toggle">${this.audio.enabled?'Desativar':'Ativar'} áudio</button><p>Controles: WASD/setas mover, mouse magia, 1-5 hotbar, E interagir, I inventário, G grimório, M mapa, Q missões, Esc pausa.</p></article></div>`}
    toast(msg){const log=document.getElementById('toastLog'),el=document.createElement('div');el.className='toast';el.textContent=msg;log.appendChild(el);setTimeout(()=>el.remove(),4200)}
    achieve(name){this.quests.achieve(name)}
  }
  window.Engine=Engine;
})();
