/* Inventário, equipamento, loja, crafting, pets, montarias e itens arrastáveis por clique. */
(function(){
  const START_ITEMS=[{id:'cajado_lua',name:'Cajado da Primeira Lua',type:'cajado',qty:1,rarity:'raro',power:8},{id:'pocao_mana',name:'Poção de Mana',type:'consumivel',qty:3,rarity:'comum'},{id:'capa_azul',name:'Capa de Aprendiz',type:'roupa',qty:1,rarity:'comum'},{id:'cristal_arcano',name:'Cristal Arcano',type:'material',qty:6,rarity:'comum'}];
  const RECIPES=[{id:'pocao_vida',name:'Poção de Vida',needs:{essencia_natureza:1,cristal_arcano:1},gives:{id:'pocao_vida',name:'Poção de Vida',type:'consumivel',qty:1,rarity:'comum'}},{id:'cajado_ignivar',name:'Cajado Ignivar',needs:{essencia_fogo:3,cristal_arcano:4},gives:{id:'cajado_ignivar',name:'Cajado Ignivar',type:'cajado',qty:1,rarity:'épico',power:22}},{id:'reliquia_lunar',name:'Relíquia da Nona Lua',needs:{essencia_arcano:5,essencia_luz:3},gives:{id:'reliquia_lunar',name:'Relíquia da Nona Lua',type:'reliquia',qty:1,rarity:'lendário',power:40}}];
  const SHOP=[{id:'mapa_antigo',name:'Mapa Antigo',type:'segredo',qty:1,rarity:'raro',price:75},{id:'ovo_corvo',name:'Pet: Corvo Astral',type:'pet',qty:1,rarity:'épico',price:120},{id:'sela_grifo',name:'Montaria: Grifo Jovem',type:'montaria',qty:1,rarity:'lendário',price:260},{id:'livro_sangue',name:'Livro de Hemomancia',type:'livro',qty:1,rarity:'raro',price:95}];
  class InventorySystem{
    constructor(engine){this.engine=engine;this.items=[];this.equipment={cajado:null,roupa:null,reliquia:null,pet:null,montaria:null};START_ITEMS.forEach(i=>this.add(i));}
    add(item){const q=item.qty||1;const ex=this.items.find(i=>i.id===item.id&&i.type===item.type);if(ex)ex.qty+=q;else this.items.push({...item,qty:q});}
    count(id){return this.items.find(i=>i.id===id)?.qty||0}
    consume(id,n=1){const it=this.items.find(i=>i.id===id);if(!it||it.qty<n)return false;it.qty-=n;if(it.qty<=0)this.items=this.items.filter(x=>x!==it);return true}
    use(id){const it=this.items.find(i=>i.id===id);if(!it)return;if(it.type==='consumivel'){if(id.includes('vida'))this.engine.player.hp=Math.min(this.engine.player.maxHp,this.engine.player.hp+55);else this.engine.player.mana=Math.min(this.engine.player.maxMana,this.engine.player.mana+70);this.consume(id);this.engine.toast(`${it.name} usada.`)}else if(['cajado','roupa','reliquia','pet','montaria'].includes(it.type)){this.equipment[it.type]=it;this.engine.toast(`${it.name} equipado.`)}else if(it.type==='livro'){this.engine.magic.unlock('fenda_tempo');this.engine.toast('Nova magia descoberta no livro!')}}
    craft(id){const r=RECIPES.find(x=>x.id===id);if(!r)return false;for(const k in r.needs)if(this.count(k)<r.needs[k])return false;for(const k in r.needs)this.consume(k,r.needs[k]);this.add(r.gives);this.engine.toast(`Criado: ${r.name}`);return true}
    buy(id){const it=SHOP.find(x=>x.id===id);if(it&&this.engine.player.gold>=it.price){this.engine.player.gold-=it.price;this.add(it);this.engine.toast(`Comprado: ${it.name}`);return true}return false}
    html(){return `<p>Ouro: <b class="rare">${this.engine.player.gold}</b> | Arraste mentalmente: clique para usar/equipar.</p><div class="grid">${this.items.map(i=>`<article class="card"><h3>${i.name}</h3><p>Tipo: ${i.type} | Quantidade: ${i.qty}</p><span class="tag ${i.rarity==='lendário'?'rare':''}">${i.rarity}</span>${i.power?`<span class="tag">Poder ${i.power}</span>`:''}<button data-use="${i.id}">Usar / equipar</button></article>`).join('')}</div>`}
    craftHtml(){return `<div class="grid">${RECIPES.map(r=>`<article class="card"><h3>${r.name}</h3><p>${Object.entries(r.needs).map(([k,v])=>`${v}× ${k}`).join(', ')}</p><button data-craft="${r.id}">Criar</button></article>`).join('')}</div>`}
    shopHtml(){return `<p>Mercadores mudam preços conforme sua reputação.</p><div class="grid">${SHOP.map(i=>`<article class="card"><h3>${i.name}</h3><p>${i.type} ${i.rarity}</p><span class="tag rare">${i.price} ouro</span><button data-buy="${i.id}">Comprar</button></article>`).join('')}</div>`}
  }
  window.GameInventory={InventorySystem,RECIPES,SHOP};
})();
