/* Inicialização, menus, criador de personagem, telas, slots e delegação dos botões. */
(function(){
  const CLASSES=['Mago elemental','Necromante','Invocador','Feiticeiro arcano','Druida','Mago do gelo','Mago de fogo','Mago sombrio','Mago celestial','Alquimista','Bruxo','Curandeiro','Ilusionista'];
  let engine;
  const $=s=>document.querySelector(s);
  function fillCreator(){const race=$('#heroRace'),klass=$('#heroClass');race.innerHTML=GameNPC.RACES.map(r=>`<option>${r}</option>`).join('');klass.innerHTML=CLASSES.map(c=>`<option>${c}</option>`).join('')}
  function screen(id){document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));['boot','menu','creator'].forEach(x=>$('#'+x)?.classList.add('hidden'));if(id){const el=$('#'+id);el.classList.remove('hidden');el.classList.add('active')}}
  function start(profile,loadData){$('#game').classList.remove('hidden');$('#menu').classList.add('hidden');$('#creator').classList.add('hidden');engine=engine||new Engine();window.game=engine;if(loadData)engine.save.apply(loadData);engine.start(profile);}
  function menuSky(){const c=$('#menuSky'),ctx=c.getContext('2d');function frame(t){c.width=innerWidth;c.height=innerHeight;const g=ctx.createLinearGradient(0,0,0,c.height);g.addColorStop(0,'#100b20');g.addColorStop(1,'#32176e');ctx.fillStyle=g;ctx.fillRect(0,0,c.width,c.height);for(let i=0;i<90;i++){const x=(i*173+t*.018*(i%5+1))%c.width,y=(i*71)%c.height;ctx.fillStyle=i%7?'rgba(141,247,255,.35)':'rgba(248,215,131,.7)';ctx.fillRect(x,y,2+(i%3),2+(i%3))}for(let i=0;i<9;i++){ctx.strokeStyle=`rgba(248,215,131,${.08+i*.025})`;ctx.beginPath();ctx.arc(c.width*.5,c.height*.45,80+i*34+(Math.sin(t/900+i)*8),0,Math.PI*2);ctx.stroke()}requestAnimationFrame(frame)}requestAnimationFrame(frame)}
  function bindUI(){window.UI={openOverlay(title,html){$('#overlayTitle').textContent=title;$('#overlayBody').innerHTML=html;$('#overlay').classList.remove('hidden')},togglePause(){if(!engine)return;engine.paused=!engine.paused;$('#pause').classList.toggle('hidden',!engine.paused);$('#pause').classList.toggle('active',engine.paused)}};$('#newGame').onclick=()=>{fillCreator();screen('creator')};$('#continueGame').onclick=()=>{const temp=engine||new Engine(),data=temp.save.load(0)||temp.save.load(1);if(data)start(null,data);else temp.toast?.('Nenhum save encontrado.')};$('#openSaves').onclick=()=>{engine=engine||new Engine();UI.openOverlay('Slots de save',engine.save.slotsHtml())};$('#openSettings').onclick=()=>{engine=engine||new Engine();UI.openOverlay('Configurações',engine.settingsHtml())};$('#startJourney').onclick=()=>{const profile={name:$('#heroName').value||'Aerin',sex:$('#heroSex').value,race:$('#heroRace').value,class:$('#heroClass').value,aura:$('#heroAura').value,cape:$('#heroCape').value};start(profile)};$('#closeOverlay').onclick=()=>$('#overlay').classList.add('hidden');$('#overlayBody').addEventListener('click',e=>{const b=e.target.closest('button');if(!b||!engine)return;if(b.dataset.use){engine.inventory.use(b.dataset.use);UI.openOverlay('Inventário',engine.inventory.html())}if(b.dataset.craft){engine.inventory.craft(b.dataset.craft);UI.openOverlay('Crafting',engine.inventory.craftHtml())}if(b.dataset.buy){engine.inventory.buy(b.dataset.buy);UI.openOverlay('Loja',engine.inventory.shopHtml())}if(b.dataset.unlock){if(engine.player.gold>=30){engine.player.gold-=30;engine.magic.unlock(b.dataset.unlock);engine.renderHotbar();UI.openOverlay('Grimório',engine.magic.grimoireHtml())}}if(b.dataset.skill){engine.magic.learnSkill(b.dataset.skill);UI.openOverlay('Árvore de habilidades',engine.magic.skillsHtml())}if(b.dataset.saveSlot){engine.save.save(+b.dataset.saveSlot);UI.openOverlay('Slots de save',engine.save.slotsHtml())}if(b.dataset.loadSlot){const data=engine.save.load(+b.dataset.loadSlot);if(data){$('#overlay').classList.add('hidden');start(null,data)}}if(b.dataset.audio){engine.audio.enabled=!engine.audio.enabled;UI.openOverlay('Configurações',engine.settingsHtml())}});$('#pause').addEventListener('click',e=>{const action=e.target.dataset.action;if(!action||!engine)return;if(action==='resume')UI.togglePause();if(action==='inventory')UI.openOverlay('Inventário',engine.inventory.html());if(action==='map')UI.openOverlay('Mapa do mundo',engine.mapHtml());if(action==='grimoire')UI.openOverlay('Grimório',engine.magic.grimoireHtml());if(action==='skills')UI.openOverlay('Árvore de habilidades',engine.magic.skillsHtml());if(action==='quests')UI.openOverlay('Missões',engine.quests.html());if(action==='save'){engine.save.save(1);engine.toast('Jogo salvo manualmente no Slot 1.')}if(action==='settings')UI.openOverlay('Configurações',engine.settingsHtml())})}
  addEventListener('DOMContentLoaded',()=>{bindUI();menuSky();setTimeout(()=>{screen('menu')},900)});
})();
