/* Céu animado, ciclo de dia/noite, chuva, neve, raios, vento, folhas e tempestades mágicas. */
(function(){
  class WeatherSystem{
    constructor(engine){this.engine=engine;this.current='folhas';this.timer=0;this.particles=[];this.lightning=0;this.wind=30;}
    update(dt){this.timer-=dt;if(this.timer<=0)this.choose();this.lightning=Math.max(0,this.lightning-dt*2);const w=this.engine.canvas.width,h=this.engine.canvas.height;const amount={chuva:5,tempestade:8,neve:3,neblina:2,raios:1,vento:2,folhas:2,tempestade_magica:6,cinzas:4,nuvens:2}[this.current]||1;for(let i=0;i<amount;i++)this.spawn(w,h);this.particles=this.particles.filter(p=>{p.x+=p.vx*dt;p.y+=p.vy*dt;p.life-=dt;if(p.y>h+30)p.life=0;return p.life>0});if((this.current==='raios'||this.current==='tempestade'||this.current==='tempestade_magica')&&Math.random()<dt*.55)this.lightning=1;}
    choose(){const b=this.engine.world.biomeAt(this.engine.player.x,this.engine.player.y);const list=b.weather;this.current=list[Math.floor(Math.random()*list.length)];this.timer=18+Math.random()*32;this.wind=-80+Math.random()*160;this.engine.toast(`Clima: ${this.label()}`)}
    label(){return {chuva:'chuva',tempestade:'tempestade',neve:'neve',neblina:'neblina',raios:'raios',vento:'ventos fortes',folhas:'folhas voando',tempestade_magica:'tempestade mágica',cinzas:'cinzas vulcânicas',nuvens:'nuvens celestiais'}[this.current]||this.current}
    spawn(w,h){let color='#fff',vx=this.wind,vy=80,size=2,life=4,x=Math.random()*w,y=-20;if(this.current==='chuva'||this.current==='tempestade'){color='#8df7ff';vy=520;size=2;life=1.5}else if(this.current==='neve'){color='#d9f4ff';vy=45;vx=this.wind*.25;size=3;life=8}else if(this.current==='folhas'){color=['#78ff72','#f8d783','#ff9a5b'][Math.floor(Math.random()*3)];vy=55;size=4;life=9}else if(this.current==='tempestade_magica'){color=['#8df7ff','#9f5cff','#ff4f9f'][Math.floor(Math.random()*3)];vy=180;size=3;life=4}else if(this.current==='cinzas'){color='#403844';vy=75;size=3;life=7}else if(this.current==='neblina'||this.current==='nuvens'){color='rgba(230,240,255,.16)';vy=8;vx=this.wind*.1;size=40+Math.random()*80;life=14;y=Math.random()*h}this.particles.push({x,y,vx,vy,color,size,life})}
    drawSky(ctx,w,h){const t=this.engine.world.time,night=this.engine.world.isNight();const grad=ctx.createLinearGradient(0,0,0,h);grad.addColorStop(0,night?'#070510':t<7?'#ba6a65':t>18?'#4b235f':'#5aa7d8');grad.addColorStop(1,night?'#151030':t>18?'#20122f':'#c4efff');ctx.fillStyle=grad;ctx.fillRect(0,0,w,h);const pos=(t/24)*w;ctx.fillStyle=night?'#dff8ff':'#fff3a8';ctx.beginPath();ctx.arc(pos,70+Math.sin(t/24*Math.PI*2)*45,night?18:28,0,Math.PI*2);ctx.fill();}
    draw(ctx,w,h){if(this.current==='neblina'){ctx.fillStyle='rgba(220,230,255,.10)';ctx.fillRect(0,0,w,h)}for(const p of this.particles){ctx.fillStyle=p.color;if(this.current==='chuva'||this.current==='tempestade'){ctx.fillRect(p.x,p.y,2,18)}else{ctx.beginPath();ctx.arc(p.x,p.y,p.size,0,Math.PI*2);ctx.fill()}}if(this.lightning>0){ctx.fillStyle=`rgba(255,255,255,${this.lightning*.45})`;ctx.fillRect(0,0,w,h)}}
  }
  window.GameWeather={WeatherSystem};
})();
